---
- name: Install and Start nginx		//Name of Playbook
  hosts: all				//List of Host where this playbook has to run
  become: true				//execute ansible playbook as root user
  become_user: userName			//for executing using specific user

  tasks:
   - name: Install nginx
     apt:
       name: nginx
       state: present
   - name: Start nginx
     service:
       name: nginx
       state: started

- name: Second PlayBook Name


#########################################################################################################

Use Case

-> Create 3 EC2 Instances on AWS	(Using Terraform)	=> Terraform Mostly used for Infrastructure management
-> Configure 1 of those EC2 instances as master	(Using Ansible)
-> Configure 2 other EC2 instances as worker	(Using Ansible)